version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

checksum:
  name_template: "checksums.txt"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/AshutoshPatole/ssm-v2/cmd.version={{.Version}} -X github.com/AshutoshPatole/ssm-v2/cmd.commit={{.Commit}} -X github.com/AshutoshPatole/ssm-v2/cmd.date={{ .CommitDate }} -X github.com/AshutoshPatole/ssm-v2/cmd.builtBy=AshutoshPatole -X github.com/AshutoshPatole/ssm-v2/cmd.treeState={{ .IsGitDirty }}

archives:
  - format: tar.gz
    name_template: >-
      ssm_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^refactor"
      - "^chore"

nfpms:
  - id: ssmv2
    package_name: ssm

    file_name_template: "{{ .ConventionalFileName }}"

    vendor: AshutoshPatole

    # Your app's homepage.
    #
    # Default: inferred from global metadata.
    homepage: https://github.com/AshutoshPatole/ssm-v2

    # Your app's maintainer (probably you).
    #
    # Default: inferred from global metadata.
    maintainer: AshutoshPatole <apatole479@gmail.com>

    # Your app's description.
    #
    # Default: inferred from global metadata.
    description: |-
      A simple SSH manager utility

    # Formats to be generated.
    formats:
      - deb
      - rpm
